credentials:
  existingSecret: cloud-credentials
  useSecret: true
  name: cloud-credentials
  key: cloud

configuration:
  backupStorageLocation:
    - name: default
      provider: azure
      bucket: velero
      config:
        resourceGroup: hamza-resources
        storageAccount: velerobackupkalech
        storageAccountKeyEnvVar: AZURE_STORAGE_ACCOUNT_ACCESS_KEY

  volumeSnapshotLocation:
    - name: default
      provider: azure
      config:
        resourceGroup: MC_hamza-resources_hamzaDevOps_eastus
        subscriptionId: 6126c082-d56e-4f42-8033-834a1072516c
        apiTimeout: 5m
        incremental: true

snapshotsEnabled: true

initContainers:
  - name: velero-plugin-for-microsoft-azure
    image: velero/velero-plugin-for-microsoft-azure:v1.7.0
    volumeMounts:
      - mountPath: /target
        name: plugins

extraVolumeMounts:
  - name: plugins
    mountPath: /plugins

extraVolumes:
  - name: plugins
    emptyDir: {}
