credentials:
  useSecret: true
  secretContents:
    cloud: |
      AZURE_STORAGE_ACCOUNT_ACCESS_KEY: 66s0msz8TYrubGX8ZMqV98+9df6yl6S+QiHmPeJ1xI0UVvKaQkHi5KeCQzb71W5Dto7f1LiFy/y5+AStXVsDng==
      AZURE_STORAGE_ACCOUNT_NAME: velerobackup96103

configuration:
  backupStorageLocation:
    - name: default
      provider: azure
      bucket: velero
      config:
        resourceGroup: hamza-resources
        storageAccount: velerobackup96103
        useAAD: "false"
        useManagedIdentity: "false"

  volumeSnapshotLocation:
    - name: default
      provider: azure
      config:
        resourceGroup: hamza-resources

initContainers:
  - name: velero-plugin-for-microsoft-azure
    image: velero/velero-plugin-for-microsoft-azure:v1.7.0
    volumeMounts:
      - mountPath: /target
        name: plugins
