credentials:
  secretContents:
    cloud: |
      AZURE_STORAGE_ACCOUNT_ACCESS_KEY: <your-storage-account-access-key>
      AZURE_STORAGE_ACCOUNT_NAME: velerobackup96103

configuration:
  backupStorageLocation:
    - name: default
      provider: azure
      bucket: velero
      config:
        resourceGroup: hamza-resources
        storageAccount: velerobackup96103

  volumeSnapshotLocation:
    - name: default
      provider: azure
      config:
        resourceGroup: hamza-resources

initContainers:
  - name: velero-plugin-for-microsoft-azure
    image: velero/velero-plugin-for-microsoft-azure:v1.7.0
    volumeMounts:
      - mountPath: /target
        name: plugins
