alertmanager:
  enabled: false

prometheus:
  prometheusSpec:
    service:
      type: ClusterIP
    storageSpec:
      volumeClaimTemplate:
        spec:
          storageClassName: azure-disk-standard
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 1Gi

grafana:
  enabled: true
  service:
    type: LoadBalancer
  adminUser: kalech
  adminPassword: grafana

nodeExporter:
  service:
    type: LoadBalancer

additionalScrapeConfigs:
  - job_name: node-exporter
    static_configs:
      - targets:
          - node-exporter:9100
  - job_name: kube-state-metrics
    static_configs:
      - targets:
          - kube-state-metrics:8080
